sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: S0LdBvyG+KwcfWVmKyDZZM0wu+w4bu4qmsfXtIaaUGdLD65OSns6Gc/GJLpzHYly4hBQbmFkDYnyK6LYSWc3apF+GCwpj4MPuH+3d27xUFqfe2DWcz5aQKuOoPamTYHCzHSGRaEegFaicEeeE5k3NJeSw777kF0hoQ/De13EskLVFAx5gIADcZSsxkjWFO0ybaZW6Sf00NVubP2lPs5Z9Iy09a8eKPogK5R5hHMYS/fD3fSVJmyLasa/c7DewKZwgwhtZbxpczXxpjgvnGRIsu97N/Vdcl+aJbZkVeLFlCCOqQBNTgKDQhuEHC4wTu218X2YTorBkzoaAuqB6Jh71Grf7lQtua8DPreNgYdyqhi7x9V6+sm5z73h8/GxmSG7qXyaGs6U3LKK8R1I5H+JyBash8WA4H6s6pZMTHu73jgTteD5QRUcgPvjQOwmfNATUeIpZWGikZR2MZ1JQCDut/Bi2Fnk6O2rEAzMzi2YZYes9zL0x3vdObTBlWmhnNAk9iOK94fwKttKYSClUAvvP6gfRn/LPdbaV5jUy7kf2cuojUnCRD+JzSjvbO3boCBaccK/sN9OR5ElhQkRA93818TPMh0Su6S+kMzDOiovtYtCPfgd6wBP9GDaPfFwYN1oR8NHlN8WnTURcgf7qNMSfAJCVbimcVvKNvGB0Np7ku0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Massimilla-Doni_1811
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy